apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-ufod
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/release-e2e-deploy-tenant/appstudio/dc-metro-map-ufod@sha256:74cf159838cc9c172d96860c308d22b3eccfbd9e79b66fa9d943f93b14d2a1eb
        name: my-nodejs
        resources: {}
status: {}
